; PlatformIO Project Configuration File for Light Trainer V3
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = xiao_esp32c3_v3
src_dir = 5_Programmation/XIAO-esp32-v3/main
include_dir = 5_Programmation/XIAO-esp32-v3/main

[env:xiao_esp32c3_v3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
board_build.partitions = min_spiffs.csv

; Dépendances de bibliothèques externes
lib_deps =
    fastled/FastLED @ ^3.6.0
    adafruit/Adafruit_VL53L0X @ ^1.2.4

; Vitesse moniteur série
monitor_speed = 115200

; Flags de compilation (USB CDC série matériel pour XIAO ESP32-C3)
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
